name: lunasea
description: Self-Hosted Controller
version: 10.0.0+1
publish_to: 'none'
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.9
  collection: ^1.15.0
  convert: ^3.0.1
  device_preview: ^1.0.0
  dio: ^4.0.4
  easy_localization: ^3.0.0
  encrypt: ^5.0.1
  envify: ^2.0.2
  expandable: ^5.0.1
  fading_edge_scrollview: ^2.0.1
  file_picker: ^4.4.0
  file_selector_macos: ^0.0.4
  file_selector_platform_interface: ^2.0.4
  firebase_auth: ^3.3.8
  firebase_core: ^1.13.0
  firebase_messaging: ^11.2.7
  firebase_storage: ^10.2.8
  fl_chart: ^0.45.0
  flash: ^2.0.3+2
  fluro: ^2.0.3
  flutter_cache_manager: ^3.3.0
  flutter_spinkit: ^5.1.0
  go_router: ^3.0.2
  google_nav_bar: ^5.0.5
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  in_app_purchase: ^1.0.9
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  layout: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  percent_indicator: ^4.0.0
  provider: ^6.0.2
  quick_actions: ^0.6.0+9
  retrofit: ^3.0.1+1
  share_plus: ^3.1.0
  shimmer: ^2.0.0
  stack_trace: ^1.10.0
  stash_memory: ^4.0.1
  supercharged: ^2.1.1
  table_calendar: ^3.0.4
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  wake_on_lan: ^2.0.3+1
  window_manager: ^0.1.7
  xml: ^5.3.1

dev_dependencies:
  # Generators
  build_runner: ^2.1.7
  envify_generator: ^2.0.2
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  retrofit_generator: ^4.0.1
  # Tooling
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.5
  # Testing
  test: ^1.20.1

dependency_overrides:
  analyzer: ^3.3.1

flutter:
  uses-material-design: true
  assets:
    # System Assets
    - assets/changelog.json
    - assets/images/
    - assets/localization/
  fonts:
    - family: LunaBrandIcons
      fonts:
        - asset: assets/LunaBrandIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: "assets/icon/icon_adaptive.png"

flutter_native_splash:
  image: "assets/images/branding_full.png"
  color: "#32323E"

scripts: derry.yaml
