name: lunasea
description: Self-Hosted Controller
version: 10.2.4+1
publish_to: "none"
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.0.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.4.5
  collection: ^1.17.0
  convert: ^3.1.1
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  dio: ^5.1.0
  easy_localization: ^3.0.1
  email_validator: ^2.1.17
  encrypt: ^5.0.1
  expandable: ^5.0.1
  file_picker: ^5.2.6
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16
  fl_chart: ^0.61.0
  flash: ^2.0.5+1
  flutter_cache_manager: ^3.3.0
  flutter_riverpod: ^2.3.2
  flutter_spinkit: ^5.1.0
  go_router: ^6.5.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  in_app_purchase: ^3.1.5
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^3.0.3
  path_provider: ^2.0.14
  percent_indicator: ^4.2.3
  quick_actions: ^1.0.2
  retrofit: ^4.0.1
  sentry_flutter: ^7.2.0
  share_plus: ^6.3.1
  shimmer: ^2.0.0
  simple_icons: ^7.10.0
  stack_trace: ^1.11.0
  stash_memory: ^4.5.2
  supercharged: ^2.1.1
  table_calendar: ^3.0.8
  transparent_image: ^2.0.1
  tuple: ^2.0.1
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  wake_on_lan: ^3.1.0+6
  window_manager: ^0.3.1
  xml: ^6.2.2

dev_dependencies:
  # Generators
  build_runner: ^2.3.3
  environment_config: ^3.1.0
  json_serializable: ^6.6.1
  hive_generator: ^2.0.0
  retrofit_generator: ^6.0.0+1
  # Tooling
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.19
  msix: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    # System Assets
    - assets/changelog.json
    - assets/changelog_stable.json
    - assets/images/
    - assets/localization/
  fonts:
    - family: LunaBrandIcons
      fonts:
        - asset: assets/LunaBrandIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: assets/icon/icon_adaptive.png

flutter_native_splash:
  image: assets/images/branding_full.png
  color: "#32323E"

msix_config:
  architecture: x64
  capabilities: internetClientServer,privateNetworkClientServer
  display_name: LunaSea
  enable_at_startup: false
  execution_alias: lunasea
  identity_name: app.lunasea.lunasea
  install_certificate: false
  logo_path: assets\icon\icon_windows.png
  output_name: lunasea-windows-amd64
  store: false
