name: lunasea
description: iOS Usenet Manager
version: 0.3.1+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  encrypt: ^4.0.0
  file_picker: ^1.4.3+1
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.6.2
  flutter_sticky_header: ^0.4.0
  http: ^0.12.0+2
  intl: ^0.16.0
  package_info: ^0.4.0+13
  path_provider: ^1.5.1
  percent_indicator: ^2.1.1+1
  shared_preferences: ^0.5.6
  url_launcher: ^5.4.1
  validators: ^2.0.0+1

dev_dependencies:
  dapackages: ^1.1.1
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/accent_color.png
    - assets/images/secondary_color.png
    - assets/images/noalbumart.png
    - assets/images/services/imdb.png
    - assets/images/services/youtube.png
    - assets/images/services/tvmaze.png
    - assets/images/services/thetvdb.png
    - assets/images/services/themoviedb.png
    - assets/images/services/discogs.png
    - assets/images/services/bandsintown.png
    - assets/images/services/lastfm.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/custom_icons/CustomIcons.ttf

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon_adaptive.png"
  adaptive_icon_background: "#32323E"

flutter_native_splash:
  image: "assets/icon/icon.png"
  color: "#32323E"
  android: false
