name: lunasea
description: Self-Hosted Controller
version: 6.0.0+60000003
publish_to: 'none'
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.2
  cloud_firestore: ^3.1.5
  convert: ^3.0.1
  dio: ^4.0.4
  easy_localization: ^3.0.0
  encrypt: ^5.0.1
  expandable: ^5.0.1
  file_picker: ^4.2.8
  file_selector_macos: ^0.0.4
  file_selector_platform_interface: ^2.0.2
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  firebase_storage: ^10.2.4
  fl_chart: ^0.40.6
  flash: ^2.0.3+1
  fluro: ^2.0.3
  flutter_spinkit: ^5.1.0
  google_nav_bar: ^5.0.5
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  in_app_purchase: ^1.0.9
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  overseerr:
    path: packages/overseerr
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  percent_indicator: ^3.4.0
  provider: ^6.0.1
  quick_actions: ^0.6.0+8
  radarr:
    path: packages/radarr
  share_plus: ^3.0.4
  sonarr:
    path: packages/sonarr
  stack_trace: ^1.10.0
  stash_memory: ^3.2.1
  supercharged: ^2.1.1
  table_calendar: ^3.0.3
  tautulli:
    path: packages/tautulli
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  wake_on_lan:
    path: packages/wake_on_lan
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 03d957e8b5c99fc83cd4a781031b154ab3de8753
  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.0.3
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
  hive_generator: ^1.1.1
  mockito: ^5.0.16
  test: ^1.20.0

flutter:
  uses-material-design: true
  assets:
    # System Assets
    - assets/changelog.json
    - assets/images/
    - assets/localization/
  fonts:
    - family: LunaBrandIcons
      fonts:
        - asset: assets/LunaBrandIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: "assets/icon/icon_adaptive.png"

flutter_native_splash:
  image: "assets/images/branding_full.png"
  color: "#32323E"

scripts: derry.yaml
